  - name: working on vm frosty
    hosts: vm # kommt aus dem hostfile, da hab ich das benannt
    tasks:
      - name: Ulli creating an empty file
        file:
          path: /home/snowman/Ulli_created_by_ansible.txt #nicht root, weil ich kein admin bin, also auf meine user-ebene
          state: touch
          owner: snowman #braucht man nicht

