  - name: working on vm frosty
    hosts: all
    remote_user: snowman
    become: true

    tasks:
      - name: creating a empty file
        file:
          path: /
          state: touch
          name: holladiewaldfee
