- name: playbook_Jenkins.yml
  hosts: vm
  become: true
  tasks: 
    - name: add key to your system
      ansible.buildin.shell:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
      keyring: /etc/apt/keyrings/jenkins.gpg

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable focal state
    
    - name: apt-get update
      ansible.builtin.shell: sudo apt-get update
    
    - name: sudo apt-get install fontconfig openjdk-11-jre
    - ansible.builtin.shell: 
        name: sudo apt-get install fontconfig openjdk-11-jre

    - name: Install the package "Jenkins"
      ansible.builtin.apt:
        name: 
          - sudo apt-get install jenkins
        state: latest

    - name: check if jenkins components are installed
      ansible.builtin.shell: dpkg -l 'jenkins' 
      register: Jenkins
      failed_when: Jenkins.stderr != ''
      changed_when: false