- hosts: 20.218.111.156 
  tasks:
  - name: Create multiple files
    file: 
      path: "{{ item }}"
      state: touch
    with_items:
    - Simonsansibletest.txt
    - Felixansibletest.txt
    - Ullisansibletest.txt